apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nginx-2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-app-cluster/argocd-app/app-2.yaml
    repoURL: https://github.com/shahnoor23/argocd-app-cluster.git
    targetRevision: HEAD
